#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace efmbchir
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="efmbchir")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Définitions de méthodes d'extensibilité
    partial void OnCreated();
    partial void Insertmissions(missions instance);
    partial void Updatemissions(missions instance);
    partial void Deletemissions(missions instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::efmbchir.Properties.Settings.Default.efmbchirConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<missions> missions
		{
			get
			{
				return this.GetTable<missions>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.missions")]
	public partial class missions : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _mission_id;
		
		private System.Nullable<int> _mission_user_id;
		
		private string _mission_name;
		
		private string _mission_description;
		
		private System.Nullable<System.DateTime> _mission_date_time;
		
		private System.Nullable<int> _mission_id_difficulty;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onmission_idChanging(int value);
    partial void Onmission_idChanged();
    partial void Onmission_user_idChanging(System.Nullable<int> value);
    partial void Onmission_user_idChanged();
    partial void Onmission_nameChanging(string value);
    partial void Onmission_nameChanged();
    partial void Onmission_descriptionChanging(string value);
    partial void Onmission_descriptionChanged();
    partial void Onmission_date_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onmission_date_timeChanged();
    partial void Onmission_id_difficultyChanging(System.Nullable<int> value);
    partial void Onmission_id_difficultyChanged();
    #endregion
		
		public missions()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mission_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int mission_id
		{
			get
			{
				return this._mission_id;
			}
			set
			{
				if ((this._mission_id != value))
				{
					this.Onmission_idChanging(value);
					this.SendPropertyChanging();
					this._mission_id = value;
					this.SendPropertyChanged("mission_id");
					this.Onmission_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mission_user_id", DbType="Int")]
		public System.Nullable<int> mission_user_id
		{
			get
			{
				return this._mission_user_id;
			}
			set
			{
				if ((this._mission_user_id != value))
				{
					this.Onmission_user_idChanging(value);
					this.SendPropertyChanging();
					this._mission_user_id = value;
					this.SendPropertyChanged("mission_user_id");
					this.Onmission_user_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mission_name", DbType="NVarChar(20)")]
		public string mission_name
		{
			get
			{
				return this._mission_name;
			}
			set
			{
				if ((this._mission_name != value))
				{
					this.Onmission_nameChanging(value);
					this.SendPropertyChanging();
					this._mission_name = value;
					this.SendPropertyChanged("mission_name");
					this.Onmission_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mission_description", DbType="NVarChar(50)")]
		public string mission_description
		{
			get
			{
				return this._mission_description;
			}
			set
			{
				if ((this._mission_description != value))
				{
					this.Onmission_descriptionChanging(value);
					this.SendPropertyChanging();
					this._mission_description = value;
					this.SendPropertyChanged("mission_description");
					this.Onmission_descriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mission_date_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> mission_date_time
		{
			get
			{
				return this._mission_date_time;
			}
			set
			{
				if ((this._mission_date_time != value))
				{
					this.Onmission_date_timeChanging(value);
					this.SendPropertyChanging();
					this._mission_date_time = value;
					this.SendPropertyChanged("mission_date_time");
					this.Onmission_date_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mission_id_difficulty", DbType="Int")]
		public System.Nullable<int> mission_id_difficulty
		{
			get
			{
				return this._mission_id_difficulty;
			}
			set
			{
				if ((this._mission_id_difficulty != value))
				{
					this.Onmission_id_difficultyChanging(value);
					this.SendPropertyChanging();
					this._mission_id_difficulty = value;
					this.SendPropertyChanged("mission_id_difficulty");
					this.Onmission_id_difficultyChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
